---
title: "Data Import"
output: github_document
---

```{r, echo = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

# Data Import: CSVs

Let's import data using the `readr` package.

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

look at the data

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

Pop up a window to view the dataset

```{r, eval = FALSE}
View(litters_df)
```

See the summary of dataset

```{r}
skimr::skim(litters_df)
```


# Options to read CSV

`red_csv` options ..

```{r, eval = FALSE}
read_csv("data/FAS_litters.csv", na = c("", "NA", 999, 88), skip = 2)
```

check out ?read_csv() for more information 


# Other file formates

we need to read in an excel spreadsheet ...

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
mlb_df = read_excel("data/mlb11.xlsx", range = "A1:F7")
```

* specific to exvel file ?read_excel

```{r, eval = FALSE}
view(mlb_df)
```

## Still more formats ...

Read in a SAS dataset.

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```






